version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cryptowallet-postgres
    environment:
      POSTGRES_DB: cryptowallet
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: cryptowallet-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: